name: Deploy Documentation (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-docs:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Setup MSVC Build Tools
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    - name: Install Visual Studio C++ Build Tools
      run: |
        choco install visualstudio2022-workload-vctools --params "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.Windows11SDK.22000"

    - name: Build Velang compiler (Release)
      run: cargo build --release

    - name: Setup MSVC environment and compile ve program
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        .\target\release\ve .\docs\server.ve

    - name: Start server in background
      run: Start-Process -NoNewWindow -FilePath "${{ github.workspace }}\docs\build\program.exe"

    - name: Wait for server to start
      run: Start-Sleep -Seconds 5

    - name: Test server endpoints
      shell: bash
      run: |
        curl -f http://localhost:8080/ || exit 1
        curl -f http://localhost:8080/getting-started || exit 1
        curl -f -s -o /dev/null -w "%{http_code}" http://localhost:8080/nonexistent | grep -q "404" || exit 1