name: Deploy Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Build Velang compiler
      run: cargo build --release
    
    - name: Compile documentation server
      run: ./target/release/ve ./docs/server.ve
    
    - name: Create systemd service
      run: |
        sudo tee /etc/systemd/system/velang-docs.service > /dev/null <<EOF
        [Unit]
        Description=Velang Documentation Server
        After=network.target
        
        [Service]
        Type=simple
        User=runner
        WorkingDirectory=${{ github.workspace }}
        ExecStart=${{ github.workspace }}/docs/build/program.exe
        Restart=always
        RestartSec=10
        
        [Install]
        WantedBy=multi-user.target
        EOF
    
    - name: Start documentation server
      run: |
        sudo systemctl daemon-reload
        sudo systemctl enable velang-docs
        sudo systemctl start velang-docs
    
    - name: Wait for server to start
      run: sleep 5
    
    - name: Test server endpoints
      run: |
        curl -f http://localhost:8080/ || exit 1
        curl -f http://localhost:8080/getting-started || exit 1
        curl -f -s -o /dev/null -w "%{http_code}" http://localhost:8080/nonexistent | grep -q "404" || exit 1
    
    - name: Setup reverse proxy (optional)
      run: |
        sudo apt-get update
        sudo apt-get install -y nginx
        sudo tee /etc/nginx/sites-available/velang-docs > /dev/null <<EOF
        server {
            listen 80;
            server_name docs.velang.org;
            
            location / {
                proxy_pass http://localhost:8080;
                proxy_set_header Host \$host;
                proxy_set_header X-Real-IP \$remote_addr;
                proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto \$scheme;
            }
        }
        EOF
        sudo ln -s /etc/nginx/sites-available/velang-docs /etc/nginx/sites-enabled/
        sudo nginx -t
        sudo systemctl restart nginx
