name: Deploy Documentation (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-docs:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build Velang compiler
      run: cargo build --release

    - name: Compile documentation server
      run: .\target\release\ve .\docs\server.ve

    - name: Start server in background
      run: Start-Process -NoNewWindow -FilePath "${{ github.workspace }}\docs\build\program.exe"

    - name: Wait for server to start
      run: Start-Sleep -Seconds 5

    - name: Test server endpoints
      shell: bash
      run: |
        curl -f http://localhost:8080/ || exit 1
        curl -f http://localhost:8080/getting-started || exit 1
        curl -f -s -o /dev/null -w "%{http_code}" http://localhost:8080/nonexistent | grep -q "404" || exit 1
